name: dogbreed
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - opencv
  - jupyter
  - tqdm
  - ipywidgets
  - pip
  - pip:
      - torch==2.7.1+cu126
      - torchvision==0.18.1+cu126
      - torchaudio==2.7.1
      - scikit-learn
      - pillow
      - streamlit
      - altair
      - --extra-index-url https://download.pytorch.org/whl/cu126